#!/usr/bin/env python3
"""Turn Apollo's existing icon SVGs into native drawing paths (no runtime SVG parser).

Run from any directory. Preserve the original foreground layers, fills and
Icon Composer positions for Apollo, Helios and Stanley; omit backgrounds.
"""
import json
from pathlib import Path
import re
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "src/settings/ApolloSpinnerArtwork.gen.h"


def path_commands(data):
    tokens = re.findall(r"[A-Za-z]|[-+]?(?:\d*\.\d+|\d+\.?\d*)(?:[eE][-+]?\d+)?", data)
    i, x, y, start_x, start_y = 0, 0, 0, 0, 0
    command = None
    control_x, control_y = 0, 0
    while i < len(tokens):
        if tokens[i].isalpha():
            command = tokens[i]
            i += 1
        upper = command.upper()
        if upper == "Z":
            yield "CGPathCloseSubpath(path);"
            x, y = start_x, start_y
            command = None
            continue
        count = {"M": 2, "L": 2, "C": 6, "S": 4}[upper]
        values = list(map(float, tokens[i:i + count]))
        i += count
        if command.islower():
            values = [v + (x if n % 2 == 0 else y) for n, v in enumerate(values)]
        if upper == "S":
            values = [2*x-control_x, 2*y-control_y] + values
        control_x, control_y = values[-4:-2] if upper in ("C", "S") else values[-2:]
        x, y = values[-2:]
        args = ", ".join(f"{v:.6f}".rstrip("0").rstrip(".") for v in values)
        if upper == "M":
            start_x, start_y = x, y
            yield f"CGPathMoveToPoint(path, NULL, {args});"
            command = "l" if command.islower() else "L"
        elif upper == "L":
            yield f"CGPathAddLineToPoint(path, NULL, {args});"
        else:
            yield f"CGPathAddCurveToPoint(path, NULL, {args});"


def color(value):
    space, components = value.split(":")
    nums = components.split(",")
    if space == "extended-gray":
        return f"[UIColor colorWithWhite:{nums[0]} alpha:{nums[1]}]"
    assert space == "display-p3"
    return f"[UIColor colorWithDisplayP3Red:{nums[0]} green:{nums[1]} blue:{nums[2]} alpha:{nums[3]}]"

lines = ["// Generated by scripts/generate-spinner-artwork.py from original icon SVGs.",
         "// Do not hand-edit. Layers use Icon Composer's 1024-point canvas.",
         '#import <UIKit/UIKit.h>', ""]
for icon_id, prefix in [("apollo", "ApolloSpinner"), ("helios", "HeliosSpinner"), ("LG-spaceship", "StanleySpinner")]:
    ICON = ROOT / f"liquid-glass/icons/{icon_id}/{icon_id}.icon"
    layers = [layer for group in json.loads((ICON / "icon.json").read_text())["groups"] for layer in group["layers"]
              if not layer.get("hidden") and not layer["name"].startswith("robotnik_bg")
              and layer["name"] != "apollo_ring_large"
              # Spinner-only variation: omit Apollo's side radio antennas.
              and not (icon_id == "apollo" and layer["name"] == "Radio_Antenna")]
    layers.reverse() # Icon Composer stores front-to-back; paint back-to-front.
    paint = []
    eye_symbol = None
    ship_pivot = None
    for index, layer in enumerate(layers):
        symbol = f"Layer{index}"
        if "eye" in layer["name"].lower():
            eye_symbol = symbol
        root = ET.parse(ICON / "Assets" / layer["image-name"]).getroot()
        vx, vy, vw, vh = map(float, root.attrib["viewBox"].split())
        width = float(root.attrib.get("width", str(vw)).removesuffix("px"))
        height = float(root.attrib.get("height", str(vh)).removesuffix("px"))
        scale = layer["position"]["scale"]
        tx, ty = layer["position"]["translation-in-points"]
        viewport = (512 + tx - width * scale / 2, 512 + ty - height * scale / 2, width * scale, height * scale)
        sx, sy = width / vw * scale, height / vh * scale
        dx, dy = 512 + tx - width * scale / 2 - vx * sx, 512 + ty - height * scale / 2 - vy * sy
        if layer["name"] == "robotnik_ship_upper":
            # Midpoint of the saucer's original straight top edge: M14.77,.5
            # followed by l46.52,16.02. Keep its actual geometry as the pivot.
            ship_pivot = (dx + (14.77 + 46.52 / 2) * sx, dy + (0.5 + 16.02 / 2) * sy)
        # These four traced source SVGs use the same original 600-point canvas.
        transforms = [e.attrib["transform"] for e in root.iter() if "transform" in e.attrib]
        if transforms:
            assert transforms == ["translate(0.000000,600.000000) scale(0.100000,-0.100000)"]
            dy += 600 * sy
            sx *= 0.1
            sy *= -0.1
        lines += [f"static CGPathRef {prefix}Create{symbol}Path(void) {{", "    CGMutablePathRef path = CGPathCreateMutable();"]
        for element in root.iter():
            tag = element.tag.rsplit("}", 1)[-1]
            if tag == "path":
                lines += ["    " + c for c in path_commands(element.attrib["d"])]
            elif tag == "circle":
                cx, cy, radius = (float(element.attrib[k]) for k in ("cx", "cy", "r"))
                lines += [f"    CGPathAddEllipseInRect(path, NULL, CGRectMake({cx-radius}, {cy-radius}, {radius*2}, {radius*2}));"]
        lines += [f"    CGAffineTransform transform = CGAffineTransformMake({sx:.8f}, 0, 0, {sy:.8f}, {dx:.8f}, {dy:.8f});",
                  "    CGPathRef result = CGPathCreateCopyByTransformingPath(path, &transform);",
                  "    CGPathRelease(path);", "    return result;", "}", ""]
        # SVG viewports clip paths. The traced helmet contains geometry above its
        # viewBox which must not appear as little white spikes beside the antenna.
        rect = ", ".join(f"{n:.8f}" for n in viewport)
        lines += [f"static CGRect {prefix}{symbol}Viewport(void) {{ return CGRectMake({rect}); }}"]
        styles = " ".join(e.text or "" for e in root.iter() if e.tag.endswith("style"))
        stroke = re.search(r"stroke-width:([\d.]+)", styles)
        stroke_width = float(stroke[1]) * min(abs(sx), abs(sy)) if stroke else 0
        lines += [f"static const CGFloat {prefix}{symbol}StrokeWidth = {stroke_width:.8f};", ""]
        # "none" means no Icon Composer fill override: retain the SVG fill.
        for appearance in ("light", "dark"):
            paint += ["    if (!dark) {" if appearance == "light" else "    else {"]
            fill = layer.get("fill")
            for match_appearance in (None, appearance):
                for spec in layer.get("fill-specializations", []):
                    if spec.get("appearance") == match_appearance:
                        fill = spec["value"]
            if not isinstance(fill, dict):
                match = re.search(r"fill:\s*(#[0-9a-fA-F]{6}|white|black)", styles)
                assert match, layer["name"]
                raw = {"white": "#ffffff", "black": "#000000"}.get(match[1], match[1])
                fill = {"solid": "display-p3:" + ",".join(str(int(raw[n:n+2],16)/255) for n in (1,3,5)) + ",1"}
            # Foreground-only spinners have no icon tile behind the antenna.
            # Lift black stems to charcoal in dark mode so they remain visible.
            if appearance == "dark" and layer["name"] in ("Stem", "robotnik_antenna"):
                fill = {"solid": "extended-gray:0.16000,1.00000"}
            paint += ["    CGContextSaveGState(ctx);",
                      f"    CGContextClipToRect(ctx, {prefix}{symbol}Viewport());",
                      f"    CGPathRef path{index} = {prefix}Create{symbol}Path();",
                      f"    CGContextAddPath(ctx, path{index});"]
            if "linear-gradient" in fill:
                orientation = fill.get("orientation", {"start": {"x": 0.5, "y": 0}, "stop": {"x": 0.5, "y": 1}})
                start, stop = orientation["start"], orientation["stop"]
                colors = ", ".join("(id)"+color(c)+".CGColor" for c in fill["linear-gradient"])
                paint += ["    CGContextClip(ctx);",
                          f"    CFArrayRef colors{index} = (__bridge CFArrayRef)@[{colors}];",
                          f"    CGGradientRef gradient{index} = CGGradientCreateWithColors(NULL, colors{index}, NULL);",
                          f"    CGRect bounds{index} = CGPathGetPathBoundingBox(path{index});",
                          f"    CGContextDrawLinearGradient(ctx, gradient{index}, CGPointMake(CGRectGetMinX(bounds{index}) + {start['x']} * bounds{index}.size.width, CGRectGetMinY(bounds{index}) + {start['y']} * bounds{index}.size.height), CGPointMake(CGRectGetMinX(bounds{index}) + {stop['x']} * bounds{index}.size.width, CGRectGetMinY(bounds{index}) + {stop['y']} * bounds{index}.size.height), kCGGradientDrawsBeforeStartLocation | kCGGradientDrawsAfterEndLocation);",
                          f"    CGGradientRelease(gradient{index});"]
            else:
                c = color(fill.get("solid", fill.get("automatic-gradient")))
                paint += [f"    CGContextSetFillColorWithColor(ctx, {c}.CGColor);",
                          f"    CGContextSetStrokeColorWithColor(ctx, {c}.CGColor);",
                          f"    CGContextSetLineWidth(ctx, {prefix}{symbol}StrokeWidth);",
                          f"    CGContextDrawPath(ctx, {prefix}{symbol}StrokeWidth > 0 ? kCGPathFillStroke : kCGPathFill);"]
            paint += [f"    CGPathRelease(path{index});", "    CGContextRestoreGState(ctx);"]
            paint += ["    }"]
    assert eye_symbol
    lines += [f"static void {prefix}Draw(CGContextRef ctx, BOOL dark) {{"]
    if ship_pivot:
        # Level the source saucer's 19-degree tilt before applying live spin.
        lines += ["    CGContextTranslateCTM(ctx, 640, 640);",
                  "    CGContextRotateCTM(ctx, -atan2(16.02, 46.52));",
                  f"    CGContextTranslateCTM(ctx, {-ship_pivot[0]:.8f}, {-ship_pivot[1]:.8f});"]
    else:
        offset = 45 if icon_id == "helios" else 0
        lines += [f"    CGPathRef eyes = {prefix}Create{eye_symbol}Path();",
                  "    CGRect eyeBounds = CGPathGetPathBoundingBox(eyes);",
                  f"    CGContextTranslateCTM(ctx, 640 - CGRectGetMidX(eyeBounds), 640 - (CGRectGetMidY(eyeBounds) - {offset}));",
                  "    CGPathRelease(eyes);"]
    lines += paint + ["}", ""]
OUTPUT.write_text("\n".join(lines))
print(OUTPUT.relative_to(ROOT))
