// Generated by scripts/generate-spinner-artwork.py from original icon SVGs.
// Do not hand-edit. Layers use Icon Composer's 1024-point canvas.
#import <UIKit/UIKit.h>

static CGPathRef ApolloSpinnerCreateLayer0Path(void) {
    CGMutablePathRef path = CGPathCreateMutable();
    CGPathMoveToPoint(path, NULL, 2801, 4709);
    CGPathAddCurveToPoint(path, NULL, 2764, 4691, 2736, 4670, 2733, 4659);
    CGPathAddCurveToPoint(path, NULL, 2730, 4649, 2723, 4640, 2717, 4640);
    CGPathAddCurveToPoint(path, NULL, 2711, 4640, 2715, 4634, 2725, 4626);
    CGPathAddCurveToPoint(path, NULL, 2736, 4618, 2748, 4614, 2753, 4617);
    CGPathAddCurveToPoint(path, NULL, 2757, 4619, 2759, 4618, 2758, 4613);
    CGPathAddCurveToPoint(path, NULL, 2754, 4601, 2796, 4549, 2804, 4557);
    CGPathAddCurveToPoint(path, NULL, 2807, 4560, 2810, 4556, 2810, 4548);
    CGPathAddCurveToPoint(path, NULL, 2810, 4539, 2816, 4529, 2823, 4526);
    CGPathAddCurveToPoint(path, NULL, 2848, 4516, 2799, 4493, 2737, 4486);
    CGPathAddCurveToPoint(path, NULL, 1990, 4402, 1309, 3878, 1065, 3198);
    CGPathAddCurveToPoint(path, NULL, 1039, 3123, 1037, 3121, 999, 3115);
    CGPathAddCurveToPoint(path, NULL, 978, 3111, 951, 3111, 940, 3115);
    CGPathAddCurveToPoint(path, NULL, 892, 3130, 817, 3109, 781, 3071);
    CGPathAddCurveToPoint(path, NULL, 597, 2876, 581, 2191, 755, 1928);
    CGPathAddCurveToPoint(path, NULL, 794, 1869, 823, 1856, 923, 1850);
    CGPathAddLineToPoint(path, NULL, 1012, 1845);
    CGPathAddLineToPoint(path, NULL, 1032, 1785);
    CGPathAddCurveToPoint(path, NULL, 1212, 1247, 1745, 831, 2439, 686);
    CGPathAddCurveToPoint(path, NULL, 2788, 613, 3212, 613, 3561, 686);
    CGPathAddCurveToPoint(path, NULL, 4251, 830, 4789, 1250, 4968, 1785);
    CGPathAddLineToPoint(path, NULL, 4988, 1845);
    CGPathAddLineToPoint(path, NULL, 5077, 1850);
    CGPathAddCurveToPoint(path, NULL, 5177, 1856, 5206, 1869, 5245, 1928);
    CGPathAddCurveToPoint(path, NULL, 5402, 2165, 5408, 2771, 5256, 3022);
    CGPathAddCurveToPoint(path, NULL, 5208, 3101, 5184, 3114, 5087, 3116);
    CGPathAddCurveToPoint(path, NULL, 5042, 3116, 4995, 3118, 4984, 3118);
    CGPathAddCurveToPoint(path, NULL, 4967, 3120, 4957, 3136, 4935, 3198);
    CGPathAddCurveToPoint(path, NULL, 4691, 3877, 4009, 4402, 3263, 4486);
    CGPathAddCurveToPoint(path, NULL, 3164, 4497, 3158, 4507, 3213, 4566);
    CGPathAddCurveToPoint(path, NULL, 3239, 4593, 3260, 4619, 3260, 4623);
    CGPathAddCurveToPoint(path, NULL, 3260, 4628, 3264, 4629, 3269, 4625);
    CGPathAddCurveToPoint(path, NULL, 3274, 4622, 3281, 4624, 3285, 4630);
    CGPathAddCurveToPoint(path, NULL, 3288, 4635, 3285, 4640, 3277, 4640);
    CGPathAddCurveToPoint(path, NULL, 3267, 4640, 3264, 4647, 3267, 4660);
    CGPathAddCurveToPoint(path, NULL, 3271, 4673, 3266, 4682, 3254, 4686);
    CGPathAddCurveToPoint(path, NULL, 3243, 4689, 3212, 4704, 3183, 4718);
    CGPathAddCurveToPoint(path, NULL, 3155, 4733, 3128, 4741, 3124, 4737);
    CGPathAddCurveToPoint(path, NULL, 3120, 4733, 3122, 4639, 3129, 4527);
    CGPathAddCurveToPoint(path, NULL, 3147, 4237, 3147, 4239, 3183, 4215);
    CGPathAddCurveToPoint(path, NULL, 3288, 4147, 3232, 4057, 3067, 4030);
    CGPathAddCurveToPoint(path, NULL, 2923, 4005, 2760, 4065, 2760, 4143);
    CGPathAddCurveToPoint(path, NULL, 2760, 4162, 2814, 4223, 2837, 4231);
    CGPathAddCurveToPoint(path, NULL, 2857, 4238, 2892, 4740, 2872, 4740);
    CGPathAddCurveToPoint(path, NULL, 2868, 4740, 2836, 4726, 2801, 4709);
    CGPathCloseSubpath(path);
    CGPathMoveToPoint(path, NULL, 3278, 3699);
    CGPathAddCurveToPoint(path, NULL, 4104, 3610, 4760, 3102, 4850, 2481);
    CGPathAddCurveToPoint(path, NULL, 4973, 1643, 4078, 860, 3000, 860);
    CGPathAddCurveToPoint(path, NULL, 1905, 860, 1006, 1664, 1155, 2511);
    CGPathAddCurveToPoint(path, NULL, 1250, 3058, 1786, 3517, 2500, 3664);
    CGPathAddCurveToPoint(path, NULL, 2720, 3709, 3051, 3724, 3278, 3699);
    CGPathCloseSubpath(path);
    CGAffineTransform transform = CGAffineTransformMake(0.17100000, 0, 0, -0.17100000, -1.32785835, 1024.22646272);
    CGPathRef result = CGPathCreateCopyByTransformingPath(path, &transform);
    CGPathRelease(path);
    return result;
}

static CGRect ApolloSpinnerLayer0Viewport(void) { return CGRectMake(99.22014165, 255.38581136, 827.55971669, 681.22837728); }
static const CGFloat ApolloSpinnerLayer0StrokeWidth = 0.00000000;

static CGPathRef ApolloSpinnerCreateLayer1Path(void) {
    CGMutablePathRef path = CGPathCreateMutable();
    CGPathMoveToPoint(path, NULL, 151.07, 0.77);
    CGPathAddCurveToPoint(path, NULL, 234.07, 0.77, 301.37, 51.99, 301.37, 115.17);
    CGPathAddCurveToPoint(path, NULL, 301.37, 178.35, 234.07, 229.57, 151.07, 229.57);
    CGPathAddCurveToPoint(path, NULL, 68.06, 229.57, 0.77, 178.35, 0.77, 115.17);
    CGPathAddCurveToPoint(path, NULL, 0.77, 51.99, 68.06, 0.77, 151.07, 0.77);
    CGPathCloseSubpath(path);
    CGAffineTransform transform = CGAffineTransformMake(2.00509714, 0, 0, 2.00355995, 209.10000000, 401.25000000);
    CGPathRef result = CGPathCreateCopyByTransformingPath(path, &transform);
    CGPathRelease(path);
    return result;
}

static CGRect ApolloSpinnerLayer1Viewport(void) { return CGRectMake(209.10000000, 401.25000000, 605.80000000, 461.50000000); }
static const CGFloat ApolloSpinnerLayer1StrokeWidth = 3.06544673;

static CGPathRef ApolloSpinnerCreateLayer2Path(void) {
    CGMutablePathRef path = CGPathCreateMutable();
    CGPathMoveToPoint(path, NULL, 13, 62.84);
    CGPathAddCurveToPoint(path, NULL, 20.18, 62.84, 26, 59.93, 26, 56.34);
    CGPathAddCurveToPoint(path, NULL, 26, 52.75, 20.18, 49.84, 13, 49.84);
    CGPathAddCurveToPoint(path, NULL, 5.82, 49.84, 0, 52.75, 0, 56.34);
    CGPathAddCurveToPoint(path, NULL, 0, 59.93, 5.82, 62.84, 13, 62.84);
    CGPathCloseSubpath(path);
    CGPathMoveToPoint(path, NULL, 21.62, 55.67);
    CGPathAddLineToPoint(path, NULL, 17.33, 0);
    CGPathAddLineToPoint(path, NULL, 8.67, 0);
    CGPathAddLineToPoint(path, NULL, 4.38, 55.67);
    CGPathAddCurveToPoint(path, NULL, 4.35, 56.09, 4.57, 56.49, 4.93, 56.7);
    CGPathAddCurveToPoint(path, NULL, 7.07, 57.9, 9.75, 58.5, 13, 58.5);
    CGPathAddCurveToPoint(path, NULL, 16.25, 58.5, 18.93, 57.9, 21.07, 56.7);
    CGPathAddCurveToPoint(path, NULL, 21.43, 56.49, 21.65, 56.09, 21.62, 55.67);
    CGPathCloseSubpath(path);
    CGAffineTransform transform = CGAffineTransformMake(3.10000000, 0, 0, 3.15722470, 471.72092639, 140.80000000);
    CGPathRef result = CGPathCreateCopyByTransformingPath(path, &transform);
    CGPathRelease(path);
    return result;
}

static CGRect ApolloSpinnerLayer2Viewport(void) { return CGRectMake(471.72092639, 140.80000000, 80.60000000, 198.40000000); }
static const CGFloat ApolloSpinnerLayer2StrokeWidth = 0.00000000;

static CGPathRef ApolloSpinnerCreateLayer3Path(void) {
    CGMutablePathRef path = CGPathCreateMutable();
    CGPathMoveToPoint(path, NULL, 2147, 2790);
    CGPathAddCurveToPoint(path, NULL, 2078, 2778, 1978, 2728, 1926, 2680);
    CGPathAddCurveToPoint(path, NULL, 1818, 2580, 1780, 2480, 1780, 2296);
    CGPathAddCurveToPoint(path, NULL, 1780, 2174, 1788, 2126, 1817, 2058);
    CGPathAddLineToPoint(path, NULL, 1833, 2021);
    CGPathAddLineToPoint(path, NULL, 1881, 2074);
    CGPathAddCurveToPoint(path, NULL, 1932, 2130, 2014, 2179, 2092, 2200);
    CGPathAddCurveToPoint(path, NULL, 2121, 2208, 2180, 2211, 2252, 2208);
    CGPathAddCurveToPoint(path, NULL, 2358, 2205, 2370, 2202, 2442, 2167);
    CGPathAddCurveToPoint(path, NULL, 2498, 2140, 2532, 2115, 2568, 2075);
    CGPathAddLineToPoint(path, NULL, 2617, 2019);
    CGPathAddLineToPoint(path, NULL, 2640, 2072);
    CGPathAddCurveToPoint(path, NULL, 2660, 2116, 2664, 2147, 2668, 2256);
    CGPathAddCurveToPoint(path, NULL, 2673, 2401, 2663, 2463, 2624, 2546);
    CGPathAddCurveToPoint(path, NULL, 2575, 2650, 2465, 2744, 2350, 2778);
    CGPathAddCurveToPoint(path, NULL, 2298, 2794, 2201, 2799, 2147, 2790);
    CGPathCloseSubpath(path);
    CGPathMoveToPoint(path, NULL, 3701, 2790);
    CGPathAddCurveToPoint(path, NULL, 3572, 2771, 3433, 2667, 3376, 2546);
    CGPathAddCurveToPoint(path, NULL, 3339, 2468, 3330, 2419, 3330, 2285);
    CGPathAddCurveToPoint(path, NULL, 3330, 2162, 3338, 2112, 3364, 2048);
    CGPathAddLineToPoint(path, NULL, 3380, 2011);
    CGPathAddLineToPoint(path, NULL, 3435, 2069);
    CGPathAddCurveToPoint(path, NULL, 3536, 2175, 3623, 2205, 3810, 2198);
    CGPathAddCurveToPoint(path, NULL, 3914, 2195, 3931, 2191, 3991, 2163);
    CGPathAddCurveToPoint(path, NULL, 4034, 2142, 4076, 2110, 4113, 2071);
    CGPathAddLineToPoint(path, NULL, 4170, 2011);
    CGPathAddLineToPoint(path, NULL, 4186, 2048);
    CGPathAddCurveToPoint(path, NULL, 4213, 2113, 4220, 2162, 4220, 2291);
    CGPathAddCurveToPoint(path, NULL, 4220, 2435, 4202, 2514, 4150, 2592);
    CGPathAddCurveToPoint(path, NULL, 4082, 2694, 3964, 2770, 3844, 2790);
    CGPathAddCurveToPoint(path, NULL, 3779, 2801, 3778, 2801, 3701, 2790);
    CGPathCloseSubpath(path);
    CGAffineTransform transform = CGAffineTransformMake(0.17000000, 0, 0, -0.17000000, 2.00000000, 1022.04000000);
    CGPathRef result = CGPathCreateCopyByTransformingPath(path, &transform);
    CGPathRelease(path);
    return result;
}

static CGRect ApolloSpinnerLayer3Viewport(void) { return CGRectMake(293.72000000, 538.56000000, 436.56000000, 146.88000000); }
static const CGFloat ApolloSpinnerLayer3StrokeWidth = 0.00000000;

static CGPathRef ApolloSpinnerCreateLayer4Path(void) {
    CGMutablePathRef path = CGPathCreateMutable();
    CGPathMoveToPoint(path, NULL, 2720, 3694);
    CGPathAddCurveToPoint(path, NULL, 2057, 3615, 1499, 3282, 1269, 2827);
    CGPathAddCurveToPoint(path, NULL, 1180, 2651, 1147, 2519, 1148, 2330);
    CGPathAddCurveToPoint(path, NULL, 1148, 2085, 1211, 1882, 1353, 1670);
    CGPathAddCurveToPoint(path, NULL, 1562, 1357, 1903, 1110, 2310, 976);
    CGPathAddCurveToPoint(path, NULL, 2846, 800, 3447, 838, 3945, 1079);
    CGPathAddCurveToPoint(path, NULL, 4421, 1309, 4745, 1686, 4835, 2115);
    CGPathAddCurveToPoint(path, NULL, 4860, 2235, 4858, 2440, 4831, 2555);
    CGPathAddCurveToPoint(path, NULL, 4740, 2933, 4493, 3226, 4070, 3457);
    CGPathAddCurveToPoint(path, NULL, 3707, 3655, 3175, 3748, 2720, 3694);
    CGPathCloseSubpath(path);
    CGPathMoveToPoint(path, NULL, 3242, 3455);
    CGPathAddCurveToPoint(path, NULL, 3802, 3390, 4237, 3155, 4476, 2788);
    CGPathAddCurveToPoint(path, NULL, 4624, 2561, 4655, 2278, 4559, 2020);
    CGPathAddCurveToPoint(path, NULL, 4362, 1490, 3707, 1106, 3000, 1106);
    CGPathAddCurveToPoint(path, NULL, 2457, 1106, 1939, 1329, 1634, 1695);
    CGPathAddCurveToPoint(path, NULL, 1383, 1995, 1318, 2349, 1457, 2663);
    CGPathAddCurveToPoint(path, NULL, 1617, 3028, 2042, 3322, 2557, 3425);
    CGPathAddCurveToPoint(path, NULL, 2779, 3470, 3027, 3480, 3242, 3455);
    CGPathCloseSubpath(path);
    CGAffineTransform transform = CGAffineTransformMake(0.17100000, 0, 0, -0.17100000, -1.00000000, 1024.82800000);
    CGPathRef result = CGPathCreateCopyByTransformingPath(path, &transform);
    CGPathRelease(path);
    return result;
}

static CGRect ApolloSpinnerLayer4Viewport(void) { return CGRectMake(185.73200000, 382.55200000, 652.53600000, 508.89600000); }
static const CGFloat ApolloSpinnerLayer4StrokeWidth = 0.00000000;

static CGPathRef ApolloSpinnerCreateLayer5Path(void) {
    CGMutablePathRef path = CGPathCreateMutable();
    CGPathAddEllipseInRect(path, NULL, CGRectMake(0.379999999999999, 0.379999999999999, 35.52, 35.52));
    CGAffineTransform transform = CGAffineTransformMake(4.18527709, 0, 0, 4.18527709, 436.10000000, 52.10000000);
    CGPathRef result = CGPathCreateCopyByTransformingPath(path, &transform);
    CGPathRelease(path);
    return result;
}

static CGRect ApolloSpinnerLayer5Viewport(void) { return CGRectMake(436.10000000, 52.10000000, 151.80000000, 151.80000000); }
static const CGFloat ApolloSpinnerLayer5StrokeWidth = 3.09710505;

static void ApolloSpinnerDraw(CGContextRef ctx, BOOL dark) {
    CGPathRef eyes = ApolloSpinnerCreateLayer3Path();
    CGRect eyeBounds = CGPathGetPathBoundingBox(eyes);
    CGContextTranslateCTM(ctx, 640 - CGRectGetMidX(eyeBounds), 640 - (CGRectGetMidY(eyeBounds) - 0));
    CGPathRelease(eyes);
    if (!dark) {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, ApolloSpinnerLayer0Viewport());
    CGPathRef path0 = ApolloSpinnerCreateLayer0Path();
    CGContextAddPath(ctx, path0);
    CGContextSetFillColorWithColor(ctx, [UIColor colorWithWhite:1.00000 alpha:1.00000].CGColor);
    CGContextSetStrokeColorWithColor(ctx, [UIColor colorWithWhite:1.00000 alpha:1.00000].CGColor);
    CGContextSetLineWidth(ctx, ApolloSpinnerLayer0StrokeWidth);
    CGContextDrawPath(ctx, ApolloSpinnerLayer0StrokeWidth > 0 ? kCGPathFillStroke : kCGPathFill);
    CGPathRelease(path0);
    CGContextRestoreGState(ctx);
    }
    else {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, ApolloSpinnerLayer0Viewport());
    CGPathRef path0 = ApolloSpinnerCreateLayer0Path();
    CGContextAddPath(ctx, path0);
    CGContextSetFillColorWithColor(ctx, [UIColor colorWithWhite:1.00000 alpha:1.00000].CGColor);
    CGContextSetStrokeColorWithColor(ctx, [UIColor colorWithWhite:1.00000 alpha:1.00000].CGColor);
    CGContextSetLineWidth(ctx, ApolloSpinnerLayer0StrokeWidth);
    CGContextDrawPath(ctx, ApolloSpinnerLayer0StrokeWidth > 0 ? kCGPathFillStroke : kCGPathFill);
    CGPathRelease(path0);
    CGContextRestoreGState(ctx);
    }
    if (!dark) {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, ApolloSpinnerLayer1Viewport());
    CGPathRef path1 = ApolloSpinnerCreateLayer1Path();
    CGContextAddPath(ctx, path1);
    CGContextSetFillColorWithColor(ctx, [UIColor colorWithWhite:1.00000 alpha:1.00000].CGColor);
    CGContextSetStrokeColorWithColor(ctx, [UIColor colorWithWhite:1.00000 alpha:1.00000].CGColor);
    CGContextSetLineWidth(ctx, ApolloSpinnerLayer1StrokeWidth);
    CGContextDrawPath(ctx, ApolloSpinnerLayer1StrokeWidth > 0 ? kCGPathFillStroke : kCGPathFill);
    CGPathRelease(path1);
    CGContextRestoreGState(ctx);
    }
    else {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, ApolloSpinnerLayer1Viewport());
    CGPathRef path1 = ApolloSpinnerCreateLayer1Path();
    CGContextAddPath(ctx, path1);
    CGContextSetFillColorWithColor(ctx, [UIColor colorWithWhite:1.00000 alpha:1.00000].CGColor);
    CGContextSetStrokeColorWithColor(ctx, [UIColor colorWithWhite:1.00000 alpha:1.00000].CGColor);
    CGContextSetLineWidth(ctx, ApolloSpinnerLayer1StrokeWidth);
    CGContextDrawPath(ctx, ApolloSpinnerLayer1StrokeWidth > 0 ? kCGPathFillStroke : kCGPathFill);
    CGPathRelease(path1);
    CGContextRestoreGState(ctx);
    }
    if (!dark) {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, ApolloSpinnerLayer2Viewport());
    CGPathRef path2 = ApolloSpinnerCreateLayer2Path();
    CGContextAddPath(ctx, path2);
    CGContextSetFillColorWithColor(ctx, [UIColor colorWithDisplayP3Red:0.20117 green:0.10448 blue:0.37405 alpha:1.00000].CGColor);
    CGContextSetStrokeColorWithColor(ctx, [UIColor colorWithDisplayP3Red:0.20117 green:0.10448 blue:0.37405 alpha:1.00000].CGColor);
    CGContextSetLineWidth(ctx, ApolloSpinnerLayer2StrokeWidth);
    CGContextDrawPath(ctx, ApolloSpinnerLayer2StrokeWidth > 0 ? kCGPathFillStroke : kCGPathFill);
    CGPathRelease(path2);
    CGContextRestoreGState(ctx);
    }
    else {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, ApolloSpinnerLayer2Viewport());
    CGPathRef path2 = ApolloSpinnerCreateLayer2Path();
    CGContextAddPath(ctx, path2);
    CGContextSetFillColorWithColor(ctx, [UIColor colorWithWhite:0.16000 alpha:1.00000].CGColor);
    CGContextSetStrokeColorWithColor(ctx, [UIColor colorWithWhite:0.16000 alpha:1.00000].CGColor);
    CGContextSetLineWidth(ctx, ApolloSpinnerLayer2StrokeWidth);
    CGContextDrawPath(ctx, ApolloSpinnerLayer2StrokeWidth > 0 ? kCGPathFillStroke : kCGPathFill);
    CGPathRelease(path2);
    CGContextRestoreGState(ctx);
    }
    if (!dark) {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, ApolloSpinnerLayer3Viewport());
    CGPathRef path3 = ApolloSpinnerCreateLayer3Path();
    CGContextAddPath(ctx, path3);
    CGContextSetFillColorWithColor(ctx, [UIColor colorWithDisplayP3Red:0.69546 green:0.15296 blue:0.47658 alpha:1.00000].CGColor);
    CGContextSetStrokeColorWithColor(ctx, [UIColor colorWithDisplayP3Red:0.69546 green:0.15296 blue:0.47658 alpha:1.00000].CGColor);
    CGContextSetLineWidth(ctx, ApolloSpinnerLayer3StrokeWidth);
    CGContextDrawPath(ctx, ApolloSpinnerLayer3StrokeWidth > 0 ? kCGPathFillStroke : kCGPathFill);
    CGPathRelease(path3);
    CGContextRestoreGState(ctx);
    }
    else {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, ApolloSpinnerLayer3Viewport());
    CGPathRef path3 = ApolloSpinnerCreateLayer3Path();
    CGContextAddPath(ctx, path3);
    CGContextSetFillColorWithColor(ctx, [UIColor colorWithDisplayP3Red:0.69546 green:0.15296 blue:0.47658 alpha:1.00000].CGColor);
    CGContextSetStrokeColorWithColor(ctx, [UIColor colorWithDisplayP3Red:0.69546 green:0.15296 blue:0.47658 alpha:1.00000].CGColor);
    CGContextSetLineWidth(ctx, ApolloSpinnerLayer3StrokeWidth);
    CGContextDrawPath(ctx, ApolloSpinnerLayer3StrokeWidth > 0 ? kCGPathFillStroke : kCGPathFill);
    CGPathRelease(path3);
    CGContextRestoreGState(ctx);
    }
    if (!dark) {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, ApolloSpinnerLayer4Viewport());
    CGPathRef path4 = ApolloSpinnerCreateLayer4Path();
    CGContextAddPath(ctx, path4);
    CGContextSetFillColorWithColor(ctx, [UIColor colorWithDisplayP3Red:0.32836 green:0.30490 blue:0.74370 alpha:1.00000].CGColor);
    CGContextSetStrokeColorWithColor(ctx, [UIColor colorWithDisplayP3Red:0.32836 green:0.30490 blue:0.74370 alpha:1.00000].CGColor);
    CGContextSetLineWidth(ctx, ApolloSpinnerLayer4StrokeWidth);
    CGContextDrawPath(ctx, ApolloSpinnerLayer4StrokeWidth > 0 ? kCGPathFillStroke : kCGPathFill);
    CGPathRelease(path4);
    CGContextRestoreGState(ctx);
    }
    else {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, ApolloSpinnerLayer4Viewport());
    CGPathRef path4 = ApolloSpinnerCreateLayer4Path();
    CGContextAddPath(ctx, path4);
    CGContextSetFillColorWithColor(ctx, [UIColor colorWithWhite:0.00000 alpha:1.00000].CGColor);
    CGContextSetStrokeColorWithColor(ctx, [UIColor colorWithWhite:0.00000 alpha:1.00000].CGColor);
    CGContextSetLineWidth(ctx, ApolloSpinnerLayer4StrokeWidth);
    CGContextDrawPath(ctx, ApolloSpinnerLayer4StrokeWidth > 0 ? kCGPathFillStroke : kCGPathFill);
    CGPathRelease(path4);
    CGContextRestoreGState(ctx);
    }
    if (!dark) {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, ApolloSpinnerLayer5Viewport());
    CGPathRef path5 = ApolloSpinnerCreateLayer5Path();
    CGContextAddPath(ctx, path5);
    CGContextSetFillColorWithColor(ctx, [UIColor colorWithWhite:1.00000 alpha:1.00000].CGColor);
    CGContextSetStrokeColorWithColor(ctx, [UIColor colorWithWhite:1.00000 alpha:1.00000].CGColor);
    CGContextSetLineWidth(ctx, ApolloSpinnerLayer5StrokeWidth);
    CGContextDrawPath(ctx, ApolloSpinnerLayer5StrokeWidth > 0 ? kCGPathFillStroke : kCGPathFill);
    CGPathRelease(path5);
    CGContextRestoreGState(ctx);
    }
    else {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, ApolloSpinnerLayer5Viewport());
    CGPathRef path5 = ApolloSpinnerCreateLayer5Path();
    CGContextAddPath(ctx, path5);
    CGContextSetFillColorWithColor(ctx, [UIColor colorWithWhite:1.00000 alpha:1.00000].CGColor);
    CGContextSetStrokeColorWithColor(ctx, [UIColor colorWithWhite:1.00000 alpha:1.00000].CGColor);
    CGContextSetLineWidth(ctx, ApolloSpinnerLayer5StrokeWidth);
    CGContextDrawPath(ctx, ApolloSpinnerLayer5StrokeWidth > 0 ? kCGPathFillStroke : kCGPathFill);
    CGPathRelease(path5);
    CGContextRestoreGState(ctx);
    }
}

static CGPathRef HeliosSpinnerCreateLayer0Path(void) {
    CGMutablePathRef path = CGPathCreateMutable();
    CGPathMoveToPoint(path, NULL, 378.82, 121.49);
    CGPathAddCurveToPoint(path, NULL, 367.65, 86.25, 344.55, 55.75, 313.9, 34.23);
    CGPathAddCurveToPoint(path, NULL, 284.06, 13.27, 247.08, 0.83, 207, 0.83);
    CGPathAddCurveToPoint(path, NULL, 167.19, 0.83, 130.35, 13.28, 100.6, 34.26);
    CGPathAddCurveToPoint(path, NULL, 70.09, 55.78, 47.03, 86.27, 35.87, 121.49);
    CGPathAddLineToPoint(path, NULL, 35.64, 121.93);
    CGPathAddLineToPoint(path, NULL, 35.08, 122.06);
    CGPathAddLineToPoint(path, NULL, 17.97, 122.06);
    CGPathAddCurveToPoint(path, NULL, 16.09, 123.03, -1.53, 133.23, 1.09, 176.54);
    CGPathAddCurveToPoint(path, NULL, 4.31, 218.44, 15.08, 227.88, 16.64, 229.03);
    CGPathAddLineToPoint(path, NULL, 29.43, 229.03);
    CGPathAddLineToPoint(path, NULL, 29.98, 229.23);
    CGPathAddLineToPoint(path, NULL, 30.19, 229.54);
    CGPathAddCurveToPoint(path, NULL, 43.96, 261.96, 68.58, 289.67, 100.07, 309.1);
    CGPathAddCurveToPoint(path, NULL, 130.66, 327.98, 167.76, 339.06, 207.7, 339.06);
    CGPathAddCurveToPoint(path, NULL, 247.64, 339.06, 284.74, 327.98, 315.34, 309.1);
    CGPathAddCurveToPoint(path, NULL, 346.82, 289.67, 371.44, 261.96, 385.22, 229.54);
    CGPathAddLineToPoint(path, NULL, 385.98, 229.03);
    CGPathAddLineToPoint(path, NULL, 398.07, 229.03);
    CGPathAddCurveToPoint(path, NULL, 399.66, 227.92, 411.02, 218.55, 413.61, 176.55);
    CGPathAddLineToPoint(path, NULL, 413.61, 176.54);
    CGPathAddCurveToPoint(path, NULL, 416.9, 133.15, 398.61, 122.99, 396.73, 122.06);
    CGPathAddLineToPoint(path, NULL, 379.61, 122.06);
    CGPathAddLineToPoint(path, NULL, 378.82, 121.49);
    CGPathCloseSubpath(path);
    CGAffineTransform transform = CGAffineTransformMake(2.08360253, 0, 0, 2.08338237, 79.87851596, 252.76269906);
    CGPathRef result = CGPathCreateCopyByTransformingPath(path, &transform);
    CGPathRelease(path);
    return result;
}

static CGRect HeliosSpinnerLayer0Viewport(void) { return CGRectMake(79.87851596, 252.76269906, 864.32000000, 708.10000000); }
static const CGFloat HeliosSpinnerLayer0StrokeWidth = 3.45841473;

static CGPathRef HeliosSpinnerCreateLayer1Path(void) {
    CGMutablePathRef path = CGPathCreateMutable();
    CGPathMoveToPoint(path, NULL, 151.07, 0.77);
    CGPathAddCurveToPoint(path, NULL, 234.07, 0.77, 301.37, 51.99, 301.37, 115.17);
    CGPathAddCurveToPoint(path, NULL, 301.37, 178.35, 234.07, 229.57, 151.07, 229.57);
    CGPathAddCurveToPoint(path, NULL, 68.06, 229.57, 0.77, 178.35, 0.77, 115.17);
    CGPathAddCurveToPoint(path, NULL, 0.77, 51.99, 68.06, 0.77, 151.07, 0.77);
    CGPathCloseSubpath(path);
    CGAffineTransform transform = CGAffineTransformMake(2.26730215, 0, 0, 2.26556395, 169.74442490, 402.40885331);
    CGPathRef result = CGPathCreateCopyByTransformingPath(path, &transform);
    CGPathRelease(path);
    return result;
}

static CGRect HeliosSpinnerLayer1Viewport(void) { return CGRectMake(169.74442490, 402.40885331, 685.02000000, 521.85000000); }
static const CGFloat HeliosSpinnerLayer1StrokeWidth = 3.46631284;

static CGPathRef HeliosSpinnerCreateLayer2Path(void) {
    CGMutablePathRef path = CGPathCreateMutable();
    CGPathMoveToPoint(path, NULL, 151.07, 0.77);
    CGPathAddCurveToPoint(path, NULL, 234.07, 0.77, 301.37, 51.99, 301.37, 115.17);
    CGPathAddCurveToPoint(path, NULL, 301.37, 178.35, 234.07, 229.57, 151.07, 229.57);
    CGPathAddCurveToPoint(path, NULL, 68.06, 229.57, 0.77, 178.35, 0.77, 115.17);
    CGPathAddCurveToPoint(path, NULL, 0.77, 51.99, 68.06, 0.77, 151.07, 0.77);
    CGPathCloseSubpath(path);
    CGAffineTransform transform = CGAffineTransformMake(2.14391156, 0, 0, 2.14226795, 188.34958716, 416.60885331);
    CGPathRef result = CGPathCreateCopyByTransformingPath(path, &transform);
    CGPathRelease(path);
    return result;
}

static CGRect HeliosSpinnerLayer2Viewport(void) { return CGRectMake(188.34958716, 416.60885331, 647.74000000, 493.45000000); }
static const CGFloat HeliosSpinnerLayer2StrokeWidth = 3.27766997;

static CGPathRef HeliosSpinnerCreateLayer3Path(void) {
    CGMutablePathRef path = CGPathCreateMutable();
    CGPathMoveToPoint(path, NULL, 549.21, 324.74);
    CGPathAddCurveToPoint(path, NULL, 550.56, 334.26, 546.97, 342.83, 538.53, 347.97);
    CGPathAddCurveToPoint(path, NULL, 522.55, 357.7, 501.46, 357.7, 485.46, 347.97);
    CGPathAddCurveToPoint(path, NULL, 477.36, 343.04, 473.38, 334.95, 474.7, 325.58);
    CGPathAddCurveToPoint(path, NULL, 474.7, 325.58, 485.54, 262.04, 495.36, 207.8);
    CGPathAddCurveToPoint(path, NULL, 500.41, 179.89, 503.35, 172.4, 511.97, 172.24);
    CGPathAddCurveToPoint(path, NULL, 520.59, 172.08, 524.08, 181.42, 528.5, 206.96);
    CGPathAddCurveToPoint(path, NULL, 537.86, 261.13, 549.21, 324.74, 549.21, 324.74);
    CGPathCloseSubpath(path);
    CGAffineTransform transform = CGAffineTransformMake(0.79000000, 0, 0, 0.79000000, 107.52000000, 40.52000000);
    CGPathRef result = CGPathCreateCopyByTransformingPath(path, &transform);
    CGPathRelease(path);
    return result;
}

static CGRect HeliosSpinnerLayer3Viewport(void) { return CGRectMake(107.52000000, 40.52000000, 808.96000000, 808.96000000); }
static const CGFloat HeliosSpinnerLayer3StrokeWidth = 0.00000000;

static CGPathRef HeliosSpinnerCreateLayer4Path(void) {
    CGMutablePathRef path = CGPathCreateMutable();
    CGPathMoveToPoint(path, NULL, 408.39, 736.45);
    CGPathAddCurveToPoint(path, NULL, 387.92, 752.24, 361.32, 752.03, 341.15, 736.65);
    CGPathAddCurveToPoint(path, NULL, 293.91, 700.65, 293.82, 612.17, 341.15, 576.04);
    CGPathAddCurveToPoint(path, NULL, 361.35, 560.61, 387.93, 560.61, 408.13, 576.04);
    CGPathAddCurveToPoint(path, NULL, 455.24, 612.02, 455.51, 700.1, 408.4, 736.44);
    CGPathCloseSubpath(path);
    CGPathMoveToPoint(path, NULL, 684.12, 736.45);
    CGPathAddCurveToPoint(path, NULL, 663.65, 752.24, 637.05, 752.03, 616.88, 736.65);
    CGPathAddCurveToPoint(path, NULL, 569.64, 700.65, 569.55, 612.17, 616.88, 576.04);
    CGPathAddCurveToPoint(path, NULL, 637.08, 560.61, 663.66, 560.61, 683.86, 576.04);
    CGPathAddCurveToPoint(path, NULL, 730.97, 612.02, 731.24, 700.1, 684.13, 736.44);
    CGPathCloseSubpath(path);
    CGAffineTransform transform = CGAffineTransformMake(1.00000000, 0, 0, 1.00000000, -0.52500943, 6.98072816);
    CGPathRef result = CGPathCreateCopyByTransformingPath(path, &transform);
    CGPathRelease(path);
    return result;
}

static CGRect HeliosSpinnerLayer4Viewport(void) { return CGRectMake(-0.52500943, 6.98072816, 1024.00000000, 1024.00000000); }
static const CGFloat HeliosSpinnerLayer4StrokeWidth = 0.00000000;

static CGPathRef HeliosSpinnerCreateLayer5Path(void) {
    CGMutablePathRef path = CGPathCreateMutable();
    CGPathAddEllipseInRect(path, NULL, CGRectMake(0.379999999999999, 0.379999999999999, 35.52, 35.52));
    CGAffineTransform transform = CGAffineTransformMake(3.45602426, 0, 0, 3.45602426, 449.30914668, 69.60217544);
    CGPathRef result = CGPathCreateCopyByTransformingPath(path, &transform);
    CGPathRelease(path);
    return result;
}

static CGRect HeliosSpinnerLayer5Viewport(void) { return CGRectMake(449.30914668, 69.60217544, 125.35000000, 125.35000000); }
static const CGFloat HeliosSpinnerLayer5StrokeWidth = 2.55745795;

static void HeliosSpinnerDraw(CGContextRef ctx, BOOL dark) {
    CGPathRef eyes = HeliosSpinnerCreateLayer4Path();
    CGRect eyeBounds = CGPathGetPathBoundingBox(eyes);
    CGContextTranslateCTM(ctx, 640 - CGRectGetMidX(eyeBounds), 640 - (CGRectGetMidY(eyeBounds) - 45));
    CGPathRelease(eyes);
    if (!dark) {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, HeliosSpinnerLayer0Viewport());
    CGPathRef path0 = HeliosSpinnerCreateLayer0Path();
    CGContextAddPath(ctx, path0);
    CGContextSetFillColorWithColor(ctx, [UIColor colorWithWhite:1.00000 alpha:1.00000].CGColor);
    CGContextSetStrokeColorWithColor(ctx, [UIColor colorWithWhite:1.00000 alpha:1.00000].CGColor);
    CGContextSetLineWidth(ctx, HeliosSpinnerLayer0StrokeWidth);
    CGContextDrawPath(ctx, HeliosSpinnerLayer0StrokeWidth > 0 ? kCGPathFillStroke : kCGPathFill);
    CGPathRelease(path0);
    CGContextRestoreGState(ctx);
    }
    else {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, HeliosSpinnerLayer0Viewport());
    CGPathRef path0 = HeliosSpinnerCreateLayer0Path();
    CGContextAddPath(ctx, path0);
    CGContextSetFillColorWithColor(ctx, [UIColor colorWithWhite:1.00000 alpha:1.00000].CGColor);
    CGContextSetStrokeColorWithColor(ctx, [UIColor colorWithWhite:1.00000 alpha:1.00000].CGColor);
    CGContextSetLineWidth(ctx, HeliosSpinnerLayer0StrokeWidth);
    CGContextDrawPath(ctx, HeliosSpinnerLayer0StrokeWidth > 0 ? kCGPathFillStroke : kCGPathFill);
    CGPathRelease(path0);
    CGContextRestoreGState(ctx);
    }
    if (!dark) {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, HeliosSpinnerLayer1Viewport());
    CGPathRef path1 = HeliosSpinnerCreateLayer1Path();
    CGContextAddPath(ctx, path1);
    CGContextSetFillColorWithColor(ctx, [UIColor colorWithWhite:0.00000 alpha:1.00000].CGColor);
    CGContextSetStrokeColorWithColor(ctx, [UIColor colorWithWhite:0.00000 alpha:1.00000].CGColor);
    CGContextSetLineWidth(ctx, HeliosSpinnerLayer1StrokeWidth);
    CGContextDrawPath(ctx, HeliosSpinnerLayer1StrokeWidth > 0 ? kCGPathFillStroke : kCGPathFill);
    CGPathRelease(path1);
    CGContextRestoreGState(ctx);
    }
    else {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, HeliosSpinnerLayer1Viewport());
    CGPathRef path1 = HeliosSpinnerCreateLayer1Path();
    CGContextAddPath(ctx, path1);
    CGContextSetFillColorWithColor(ctx, [UIColor colorWithWhite:0.00000 alpha:1.00000].CGColor);
    CGContextSetStrokeColorWithColor(ctx, [UIColor colorWithWhite:0.00000 alpha:1.00000].CGColor);
    CGContextSetLineWidth(ctx, HeliosSpinnerLayer1StrokeWidth);
    CGContextDrawPath(ctx, HeliosSpinnerLayer1StrokeWidth > 0 ? kCGPathFillStroke : kCGPathFill);
    CGPathRelease(path1);
    CGContextRestoreGState(ctx);
    }
    if (!dark) {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, HeliosSpinnerLayer2Viewport());
    CGPathRef path2 = HeliosSpinnerCreateLayer2Path();
    CGContextAddPath(ctx, path2);
    CGContextClip(ctx);
    CFArrayRef colors2 = (__bridge CFArrayRef)@[(id)[UIColor colorWithDisplayP3Red:0.18720 green:0.09577 blue:0.33307 alpha:1.00000].CGColor, (id)[UIColor colorWithWhite:0.00000 alpha:1.00000].CGColor];
    CGGradientRef gradient2 = CGGradientCreateWithColors(NULL, colors2, NULL);
    CGRect bounds2 = CGPathGetPathBoundingBox(path2);
    CGContextDrawLinearGradient(ctx, gradient2, CGPointMake(CGRectGetMinX(bounds2) + 0.5 * bounds2.size.width, CGRectGetMinY(bounds2) + 0 * bounds2.size.height), CGPointMake(CGRectGetMinX(bounds2) + 0.5 * bounds2.size.width, CGRectGetMinY(bounds2) + 1 * bounds2.size.height), kCGGradientDrawsBeforeStartLocation | kCGGradientDrawsAfterEndLocation);
    CGGradientRelease(gradient2);
    CGPathRelease(path2);
    CGContextRestoreGState(ctx);
    }
    else {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, HeliosSpinnerLayer2Viewport());
    CGPathRef path2 = HeliosSpinnerCreateLayer2Path();
    CGContextAddPath(ctx, path2);
    CGContextClip(ctx);
    CFArrayRef colors2 = (__bridge CFArrayRef)@[(id)[UIColor colorWithWhite:0.25000 alpha:1.00000].CGColor, (id)[UIColor colorWithDisplayP3Red:0.12828 green:0.12671 blue:0.12671 alpha:1.00000].CGColor];
    CGGradientRef gradient2 = CGGradientCreateWithColors(NULL, colors2, NULL);
    CGRect bounds2 = CGPathGetPathBoundingBox(path2);
    CGContextDrawLinearGradient(ctx, gradient2, CGPointMake(CGRectGetMinX(bounds2) + 0.5 * bounds2.size.width, CGRectGetMinY(bounds2) + 0 * bounds2.size.height), CGPointMake(CGRectGetMinX(bounds2) + 0.5 * bounds2.size.width, CGRectGetMinY(bounds2) + 0.7 * bounds2.size.height), kCGGradientDrawsBeforeStartLocation | kCGGradientDrawsAfterEndLocation);
    CGGradientRelease(gradient2);
    CGPathRelease(path2);
    CGContextRestoreGState(ctx);
    }
    if (!dark) {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, HeliosSpinnerLayer3Viewport());
    CGPathRef path3 = HeliosSpinnerCreateLayer3Path();
    CGContextAddPath(ctx, path3);
    CGContextSetFillColorWithColor(ctx, [UIColor colorWithDisplayP3Red:0.2196078431372549 green:0.09411764705882353 blue:0.396078431372549 alpha:1].CGColor);
    CGContextSetStrokeColorWithColor(ctx, [UIColor colorWithDisplayP3Red:0.2196078431372549 green:0.09411764705882353 blue:0.396078431372549 alpha:1].CGColor);
    CGContextSetLineWidth(ctx, HeliosSpinnerLayer3StrokeWidth);
    CGContextDrawPath(ctx, HeliosSpinnerLayer3StrokeWidth > 0 ? kCGPathFillStroke : kCGPathFill);
    CGPathRelease(path3);
    CGContextRestoreGState(ctx);
    }
    else {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, HeliosSpinnerLayer3Viewport());
    CGPathRef path3 = HeliosSpinnerCreateLayer3Path();
    CGContextAddPath(ctx, path3);
    CGContextSetFillColorWithColor(ctx, [UIColor colorWithDisplayP3Red:0.12829 green:0.12671 blue:0.12671 alpha:1.00000].CGColor);
    CGContextSetStrokeColorWithColor(ctx, [UIColor colorWithDisplayP3Red:0.12829 green:0.12671 blue:0.12671 alpha:1.00000].CGColor);
    CGContextSetLineWidth(ctx, HeliosSpinnerLayer3StrokeWidth);
    CGContextDrawPath(ctx, HeliosSpinnerLayer3StrokeWidth > 0 ? kCGPathFillStroke : kCGPathFill);
    CGPathRelease(path3);
    CGContextRestoreGState(ctx);
    }
    if (!dark) {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, HeliosSpinnerLayer4Viewport());
    CGPathRef path4 = HeliosSpinnerCreateLayer4Path();
    CGContextAddPath(ctx, path4);
    CGContextSetFillColorWithColor(ctx, [UIColor colorWithDisplayP3Red:0.89418 green:0.06660 blue:0.83887 alpha:1.00000].CGColor);
    CGContextSetStrokeColorWithColor(ctx, [UIColor colorWithDisplayP3Red:0.89418 green:0.06660 blue:0.83887 alpha:1.00000].CGColor);
    CGContextSetLineWidth(ctx, HeliosSpinnerLayer4StrokeWidth);
    CGContextDrawPath(ctx, HeliosSpinnerLayer4StrokeWidth > 0 ? kCGPathFillStroke : kCGPathFill);
    CGPathRelease(path4);
    CGContextRestoreGState(ctx);
    }
    else {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, HeliosSpinnerLayer4Viewport());
    CGPathRef path4 = HeliosSpinnerCreateLayer4Path();
    CGContextAddPath(ctx, path4);
    CGContextSetFillColorWithColor(ctx, [UIColor colorWithDisplayP3Red:0.89418 green:0.06660 blue:0.83887 alpha:1.00000].CGColor);
    CGContextSetStrokeColorWithColor(ctx, [UIColor colorWithDisplayP3Red:0.89418 green:0.06660 blue:0.83887 alpha:1.00000].CGColor);
    CGContextSetLineWidth(ctx, HeliosSpinnerLayer4StrokeWidth);
    CGContextDrawPath(ctx, HeliosSpinnerLayer4StrokeWidth > 0 ? kCGPathFillStroke : kCGPathFill);
    CGPathRelease(path4);
    CGContextRestoreGState(ctx);
    }
    if (!dark) {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, HeliosSpinnerLayer5Viewport());
    CGPathRef path5 = HeliosSpinnerCreateLayer5Path();
    CGContextAddPath(ctx, path5);
    CGContextSetFillColorWithColor(ctx, [UIColor colorWithWhite:1.00000 alpha:1.00000].CGColor);
    CGContextSetStrokeColorWithColor(ctx, [UIColor colorWithWhite:1.00000 alpha:1.00000].CGColor);
    CGContextSetLineWidth(ctx, HeliosSpinnerLayer5StrokeWidth);
    CGContextDrawPath(ctx, HeliosSpinnerLayer5StrokeWidth > 0 ? kCGPathFillStroke : kCGPathFill);
    CGPathRelease(path5);
    CGContextRestoreGState(ctx);
    }
    else {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, HeliosSpinnerLayer5Viewport());
    CGPathRef path5 = HeliosSpinnerCreateLayer5Path();
    CGContextAddPath(ctx, path5);
    CGContextSetFillColorWithColor(ctx, [UIColor colorWithWhite:1.00000 alpha:1.00000].CGColor);
    CGContextSetStrokeColorWithColor(ctx, [UIColor colorWithWhite:1.00000 alpha:1.00000].CGColor);
    CGContextSetLineWidth(ctx, HeliosSpinnerLayer5StrokeWidth);
    CGContextDrawPath(ctx, HeliosSpinnerLayer5StrokeWidth > 0 ? kCGPathFillStroke : kCGPathFill);
    CGPathRelease(path5);
    CGContextRestoreGState(ctx);
    }
}

static CGPathRef StanleySpinnerCreateLayer0Path(void) {
    CGMutablePathRef path = CGPathCreateMutable();
    CGPathMoveToPoint(path, NULL, 3.89, 0);
    CGPathAddCurveToPoint(path, NULL, 4.04, -0.01, 4.21, 0.04, 4.33, 0.16);
    CGPathAddLineToPoint(path, NULL, 7.62, 3.5);
    CGPathAddCurveToPoint(path, NULL, 7.83, 3.71, 7.83, 4.05, 7.62, 4.26);
    CGPathAddCurveToPoint(path, NULL, 7.41, 4.46, 7.07, 4.46, 6.87, 4.25);
    CGPathAddLineToPoint(path, NULL, 3.89, 1.22);
    CGPathAddLineToPoint(path, NULL, 0.91, 4.25);
    CGPathAddCurveToPoint(path, NULL, 0.7, 4.46, 0.37, 4.46, 0.16, 4.26);
    CGPathAddCurveToPoint(path, NULL, -0.05, 4.05, -0.05, 3.71, 0.15, 3.5);
    CGPathAddLineToPoint(path, NULL, 3.45, 0.16);
    CGPathAddCurveToPoint(path, NULL, 3.57, 0.04, 3.73, -0.01, 3.89, 0);
    CGPathCloseSubpath(path);
    CGAffineTransform transform = CGAffineTransformMake(30.31362468, 0, 0, 30.38548753, 577.08000000, 169.00000000);
    CGPathRef result = CGPathCreateCopyByTransformingPath(path, &transform);
    CGPathRelease(path);
    return result;
}

static CGRect StanleySpinnerLayer0Viewport(void) { return CGRectMake(577.08000000, 169.00000000, 235.84000000, 134.00000000); }
static const CGFloat StanleySpinnerLayer0StrokeWidth = 0.00000000;

static CGPathRef StanleySpinnerCreateLayer1Path(void) {
    CGMutablePathRef path = CGPathCreateMutable();
    CGPathMoveToPoint(path, NULL, 28.75, 0.94);
    CGPathAddLineToPoint(path, NULL, 29.23, 1.11);
    CGPathAddCurveToPoint(path, NULL, 38.26, 4.22, 43.11, 14.15, 40, 23.18);
    CGPathAddLineToPoint(path, NULL, 33.31, 42.58);
    CGPathAddLineToPoint(path, NULL, 0, 31.11);
    CGPathAddLineToPoint(path, NULL, 6.68, 11.7);
    CGPathAddCurveToPoint(path, NULL, 9.79, 2.68, 19.72, -2.17, 28.75, 0.94);
    CGPathCloseSubpath(path);
    CGAffineTransform transform = CGAffineTransformMake(12.37225208, 0, 0, 12.36777830, 244.74000000, 253.69000000);
    CGPathRef result = CGPathCreateCopyByTransformingPath(path, &transform);
    CGPathRelease(path);
    return result;
}

static CGRect StanleySpinnerLayer1Viewport(void) { return CGRectMake(244.74000000, 253.69000000, 506.52000000, 526.62000000); }
static const CGFloat StanleySpinnerLayer1StrokeWidth = 0.00000000;

static CGPathRef StanleySpinnerCreateLayer2Path(void) {
    CGMutablePathRef path = CGPathCreateMutable();
    CGPathMoveToPoint(path, NULL, 3.08, 16.1);
    CGPathAddLineToPoint(path, NULL, 47.37, 31.35);
    CGPathAddCurveToPoint(path, NULL, 49.75, 32.17, 52.36, 30.89, 53.18, 28.51);
    CGPathAddLineToPoint(path, NULL, 56.72, 18.23);
    CGPathAddLineToPoint(path, NULL, 3.79, 0);
    CGPathAddLineToPoint(path, NULL, 0.25, 10.29);
    CGPathAddCurveToPoint(path, NULL, -0.57, 12.67, 0.7, 15.28, 3.08, 16.1);
    CGPathCloseSubpath(path);
    CGAffineTransform transform = CGAffineTransformMake(10.31734838, 0, 0, 10.31170886, 189.40000000, 473.07500000);
    CGPathRef result = CGPathCreateCopyByTransformingPath(path, &transform);
    CGPathRelease(path);
    return result;
}

static CGRect StanleySpinnerLayer2Viewport(void) { return CGRectMake(189.40000000, 473.07500000, 585.20000000, 325.85000000); }
static const CGFloat StanleySpinnerLayer2StrokeWidth = 0.00000000;

static CGPathRef StanleySpinnerCreateLayer3Path(void) {
    CGMutablePathRef path = CGPathCreateMutable();
    CGPathMoveToPoint(path, NULL, 14.77, 0.5);
    CGPathAddLineToPoint(path, NULL, 61.29, 16.52);
    CGPathAddCurveToPoint(path, NULL, 66.07, 18.17, 68.64, 23.42, 66.99, 28.2);
    CGPathAddLineToPoint(path, NULL, 63.91, 37.15);
    CGPathAddLineToPoint(path, NULL, 0, 15.15);
    CGPathAddLineToPoint(path, NULL, 3.08, 6.2);
    CGPathAddCurveToPoint(path, NULL, 4.73, 1.42, 9.99, -1.15, 14.77, 0.5);
    CGPathCloseSubpath(path);
    CGAffineTransform transform = CGAffineTransformMake(9.49059120, 0, 0, 9.48640646, 171.74000000, 391.79000000);
    CGPathRef result = CGPathCreateCopyByTransformingPath(path, &transform);
    CGPathRelease(path);
    return result;
}

static CGRect StanleySpinnerLayer3Viewport(void) { return CGRectMake(171.74000000, 391.79000000, 640.52000000, 352.42000000); }
static const CGFloat StanleySpinnerLayer3StrokeWidth = 0.00000000;

static CGPathRef StanleySpinnerCreateLayer4Path(void) {
    CGMutablePathRef path = CGPathCreateMutable();
    CGPathMoveToPoint(path, NULL, 7.17, 1.95);
    CGPathAddCurveToPoint(path, NULL, 8, 1.95, 8.66, 2.61, 8.66, 3.44);
    CGPathAddCurveToPoint(path, NULL, 8.66, 4.26, 8, 4.93, 7.17, 4.93);
    CGPathAddCurveToPoint(path, NULL, 6.35, 4.93, 5.68, 4.26, 5.68, 3.44);
    CGPathAddCurveToPoint(path, NULL, 5.68, 2.61, 6.35, 1.95, 7.17, 1.95);
    CGPathCloseSubpath(path);
    CGPathMoveToPoint(path, NULL, 1.49, 0);
    CGPathAddCurveToPoint(path, NULL, 2.31, 0, 2.98, 0.67, 2.98, 1.49);
    CGPathAddCurveToPoint(path, NULL, 2.98, 2.31, 2.31, 2.98, 1.49, 2.98);
    CGPathAddCurveToPoint(path, NULL, 0.67, 2.98, 0, 2.31, 0, 1.49);
    CGPathAddCurveToPoint(path, NULL, 0, 0.67, 0.67, 0, 1.49, 0);
    CGPathCloseSubpath(path);
    CGAffineTransform transform = CGAffineTransformMake(28.42494226, 0, 0, 28.41379310, 436.92000000, 324.96000000);
    CGPathRef result = CGPathCreateCopyByTransformingPath(path, &transform);
    CGPathRelease(path);
    return result;
}

static CGRect StanleySpinnerLayer4Viewport(void) { return CGRectMake(436.92000000, 324.96000000, 246.16000000, 140.08000000); }
static const CGFloat StanleySpinnerLayer4StrokeWidth = 0.00000000;

static CGPathRef StanleySpinnerCreateLayer5Path(void) {
    CGMutablePathRef path = CGPathCreateMutable();
    CGPathAddEllipseInRect(path, NULL, CGRectMake(0.0, 0.0, 23.26, 23.26));
    CGAffineTransform transform = CGAffineTransformMake(4.62365591, 0, 0, 4.62365591, 754.25000000, 247.25000000);
    CGPathRef result = CGPathCreateCopyByTransformingPath(path, &transform);
    CGPathRelease(path);
    return result;
}

static CGRect StanleySpinnerLayer5Viewport(void) { return CGRectMake(754.25000000, 247.25000000, 107.50000000, 107.50000000); }
static const CGFloat StanleySpinnerLayer5StrokeWidth = 0.00000000;

static void StanleySpinnerDraw(CGContextRef ctx, BOOL dark) {
    CGContextTranslateCTM(ctx, 640, 640);
    CGContextRotateCTM(ctx, -atan2(16.02, 46.52));
    CGContextTranslateCTM(ctx, -532.66718329, -472.51931898);
    if (!dark) {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, StanleySpinnerLayer0Viewport());
    CGPathRef path0 = StanleySpinnerCreateLayer0Path();
    CGContextAddPath(ctx, path0);
    CGContextSetFillColorWithColor(ctx, [UIColor colorWithWhite:0.00000 alpha:1.00000].CGColor);
    CGContextSetStrokeColorWithColor(ctx, [UIColor colorWithWhite:0.00000 alpha:1.00000].CGColor);
    CGContextSetLineWidth(ctx, StanleySpinnerLayer0StrokeWidth);
    CGContextDrawPath(ctx, StanleySpinnerLayer0StrokeWidth > 0 ? kCGPathFillStroke : kCGPathFill);
    CGPathRelease(path0);
    CGContextRestoreGState(ctx);
    }
    else {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, StanleySpinnerLayer0Viewport());
    CGPathRef path0 = StanleySpinnerCreateLayer0Path();
    CGContextAddPath(ctx, path0);
    CGContextSetFillColorWithColor(ctx, [UIColor colorWithWhite:0.16000 alpha:1.00000].CGColor);
    CGContextSetStrokeColorWithColor(ctx, [UIColor colorWithWhite:0.16000 alpha:1.00000].CGColor);
    CGContextSetLineWidth(ctx, StanleySpinnerLayer0StrokeWidth);
    CGContextDrawPath(ctx, StanleySpinnerLayer0StrokeWidth > 0 ? kCGPathFillStroke : kCGPathFill);
    CGPathRelease(path0);
    CGContextRestoreGState(ctx);
    }
    if (!dark) {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, StanleySpinnerLayer1Viewport());
    CGPathRef path1 = StanleySpinnerCreateLayer1Path();
    CGContextAddPath(ctx, path1);
    CGContextSetFillColorWithColor(ctx, [UIColor colorWithDisplayP3Red:0.96924 green:0.97070 blue:0.97070 alpha:1.00000].CGColor);
    CGContextSetStrokeColorWithColor(ctx, [UIColor colorWithDisplayP3Red:0.96924 green:0.97070 blue:0.97070 alpha:1.00000].CGColor);
    CGContextSetLineWidth(ctx, StanleySpinnerLayer1StrokeWidth);
    CGContextDrawPath(ctx, StanleySpinnerLayer1StrokeWidth > 0 ? kCGPathFillStroke : kCGPathFill);
    CGPathRelease(path1);
    CGContextRestoreGState(ctx);
    }
    else {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, StanleySpinnerLayer1Viewport());
    CGPathRef path1 = StanleySpinnerCreateLayer1Path();
    CGContextAddPath(ctx, path1);
    CGContextSetFillColorWithColor(ctx, [UIColor colorWithDisplayP3Red:0.9686274509803922 green:0.9686274509803922 blue:0.9686274509803922 alpha:1].CGColor);
    CGContextSetStrokeColorWithColor(ctx, [UIColor colorWithDisplayP3Red:0.9686274509803922 green:0.9686274509803922 blue:0.9686274509803922 alpha:1].CGColor);
    CGContextSetLineWidth(ctx, StanleySpinnerLayer1StrokeWidth);
    CGContextDrawPath(ctx, StanleySpinnerLayer1StrokeWidth > 0 ? kCGPathFillStroke : kCGPathFill);
    CGPathRelease(path1);
    CGContextRestoreGState(ctx);
    }
    if (!dark) {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, StanleySpinnerLayer2Viewport());
    CGPathRef path2 = StanleySpinnerCreateLayer2Path();
    CGContextAddPath(ctx, path2);
    CGContextSetFillColorWithColor(ctx, [UIColor colorWithDisplayP3Red:0.64261 green:0.64891 blue:0.65772 alpha:1.00000].CGColor);
    CGContextSetStrokeColorWithColor(ctx, [UIColor colorWithDisplayP3Red:0.64261 green:0.64891 blue:0.65772 alpha:1.00000].CGColor);
    CGContextSetLineWidth(ctx, StanleySpinnerLayer2StrokeWidth);
    CGContextDrawPath(ctx, StanleySpinnerLayer2StrokeWidth > 0 ? kCGPathFillStroke : kCGPathFill);
    CGPathRelease(path2);
    CGContextRestoreGState(ctx);
    }
    else {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, StanleySpinnerLayer2Viewport());
    CGPathRef path2 = StanleySpinnerCreateLayer2Path();
    CGContextAddPath(ctx, path2);
    CGContextSetFillColorWithColor(ctx, [UIColor colorWithWhite:0.50000 alpha:1.00000].CGColor);
    CGContextSetStrokeColorWithColor(ctx, [UIColor colorWithWhite:0.50000 alpha:1.00000].CGColor);
    CGContextSetLineWidth(ctx, StanleySpinnerLayer2StrokeWidth);
    CGContextDrawPath(ctx, StanleySpinnerLayer2StrokeWidth > 0 ? kCGPathFillStroke : kCGPathFill);
    CGPathRelease(path2);
    CGContextRestoreGState(ctx);
    }
    if (!dark) {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, StanleySpinnerLayer3Viewport());
    CGPathRef path3 = StanleySpinnerCreateLayer3Path();
    CGContextAddPath(ctx, path3);
    CGContextSetFillColorWithColor(ctx, [UIColor colorWithDisplayP3Red:0.82277 green:0.82763 blue:0.83301 alpha:1.00000].CGColor);
    CGContextSetStrokeColorWithColor(ctx, [UIColor colorWithDisplayP3Red:0.82277 green:0.82763 blue:0.83301 alpha:1.00000].CGColor);
    CGContextSetLineWidth(ctx, StanleySpinnerLayer3StrokeWidth);
    CGContextDrawPath(ctx, StanleySpinnerLayer3StrokeWidth > 0 ? kCGPathFillStroke : kCGPathFill);
    CGPathRelease(path3);
    CGContextRestoreGState(ctx);
    }
    else {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, StanleySpinnerLayer3Viewport());
    CGPathRef path3 = StanleySpinnerCreateLayer3Path();
    CGContextAddPath(ctx, path3);
    CGContextSetFillColorWithColor(ctx, [UIColor colorWithWhite:0.75000 alpha:1.00000].CGColor);
    CGContextSetStrokeColorWithColor(ctx, [UIColor colorWithWhite:0.75000 alpha:1.00000].CGColor);
    CGContextSetLineWidth(ctx, StanleySpinnerLayer3StrokeWidth);
    CGContextDrawPath(ctx, StanleySpinnerLayer3StrokeWidth > 0 ? kCGPathFillStroke : kCGPathFill);
    CGPathRelease(path3);
    CGContextRestoreGState(ctx);
    }
    if (!dark) {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, StanleySpinnerLayer4Viewport());
    CGPathRef path4 = StanleySpinnerCreateLayer4Path();
    CGContextAddPath(ctx, path4);
    CGContextSetFillColorWithColor(ctx, [UIColor colorWithDisplayP3Red:0.90311 green:0.19759 blue:0.28048 alpha:1.00000].CGColor);
    CGContextSetStrokeColorWithColor(ctx, [UIColor colorWithDisplayP3Red:0.90311 green:0.19759 blue:0.28048 alpha:1.00000].CGColor);
    CGContextSetLineWidth(ctx, StanleySpinnerLayer4StrokeWidth);
    CGContextDrawPath(ctx, StanleySpinnerLayer4StrokeWidth > 0 ? kCGPathFillStroke : kCGPathFill);
    CGPathRelease(path4);
    CGContextRestoreGState(ctx);
    }
    else {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, StanleySpinnerLayer4Viewport());
    CGPathRef path4 = StanleySpinnerCreateLayer4Path();
    CGContextAddPath(ctx, path4);
    CGContextSetFillColorWithColor(ctx, [UIColor colorWithDisplayP3Red:0.90311 green:0.19759 blue:0.28048 alpha:1.00000].CGColor);
    CGContextSetStrokeColorWithColor(ctx, [UIColor colorWithDisplayP3Red:0.90311 green:0.19759 blue:0.28048 alpha:1.00000].CGColor);
    CGContextSetLineWidth(ctx, StanleySpinnerLayer4StrokeWidth);
    CGContextDrawPath(ctx, StanleySpinnerLayer4StrokeWidth > 0 ? kCGPathFillStroke : kCGPathFill);
    CGPathRelease(path4);
    CGContextRestoreGState(ctx);
    }
    if (!dark) {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, StanleySpinnerLayer5Viewport());
    CGPathRef path5 = StanleySpinnerCreateLayer5Path();
    CGContextAddPath(ctx, path5);
    CGContextSetFillColorWithColor(ctx, [UIColor colorWithWhite:1.00000 alpha:1.00000].CGColor);
    CGContextSetStrokeColorWithColor(ctx, [UIColor colorWithWhite:1.00000 alpha:1.00000].CGColor);
    CGContextSetLineWidth(ctx, StanleySpinnerLayer5StrokeWidth);
    CGContextDrawPath(ctx, StanleySpinnerLayer5StrokeWidth > 0 ? kCGPathFillStroke : kCGPathFill);
    CGPathRelease(path5);
    CGContextRestoreGState(ctx);
    }
    else {
    CGContextSaveGState(ctx);
    CGContextClipToRect(ctx, StanleySpinnerLayer5Viewport());
    CGPathRef path5 = StanleySpinnerCreateLayer5Path();
    CGContextAddPath(ctx, path5);
    CGContextSetFillColorWithColor(ctx, [UIColor colorWithDisplayP3Red:1.0 green:1.0 blue:1.0 alpha:1].CGColor);
    CGContextSetStrokeColorWithColor(ctx, [UIColor colorWithDisplayP3Red:1.0 green:1.0 blue:1.0 alpha:1].CGColor);
    CGContextSetLineWidth(ctx, StanleySpinnerLayer5StrokeWidth);
    CGContextDrawPath(ctx, StanleySpinnerLayer5StrokeWidth > 0 ? kCGPathFillStroke : kCGPathFill);
    CGPathRelease(path5);
    CGContextRestoreGState(ctx);
    }
}
